export const jenjang = [
  {
    kodeProdi: 110110,
    programStudi: "Hukum",
    jenjang: "Sarjana",
    kodeDSpace: 215,
    owningCollection: "code here",
  },
  {
    kodeProdi: 110120,
    programStudi: "Hukum",
    jenjang: "Magister",
    kodeDSpace: 218,
    owningCollection: "code here",
  },
  {
    kodeProdi: 110130,
    programStudi: "Hukum",
    jenjang: "Doktor",
    kodeDSpace: 220,
    owningCollection: "code here",
  },
  {
    kodeProdi: 110620,
    programStudi: "Kenotariatan",
    jenjang: "Magister",
    kodeDSpace: 219,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120103,
    programStudi: "Akuntansi",
    jenjang: "Diploma III",
    kodeDSpace: 295,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120104,
    programStudi: "Akuntansi Perpajakan",
    jenjang: "Diploma IV",
    kodeDSpace: 195,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120110,
    programStudi: "Akuntansi",
    jenjang: "Sarjana",
    kodeDSpace: 200,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120120,
    programStudi: "Ekonomi",
    jenjang: "Magister",
    kodeDSpace: 209,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120130,
    programStudi: "Ekonomi",
    jenjang: "Doktor",
    kodeDSpace: 211,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120203,
    programStudi: "Manajemen Pemasaran",
    jenjang: "Diploma III",
    kodeDSpace: 296,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120204,
    programStudi: "Akuntansi Sektor Publik",
    jenjang: "Diploma IV",
    kodeDSpace: 196,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120210,
    programStudi: "Ekonomi Pembangunan",
    jenjang: "Sarjana",
    kodeDSpace: 317,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120303,
    programStudi: "Administrasi Perpajakan",
    jenjang: "Diploma III",
    kodeDSpace: 297,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120304,
    programStudi: "Bisnis Internasional",
    jenjang: "Diploma IV",
    kodeDSpace: 197,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120310,
    programStudi: "Manajemen",
    jenjang: "Sarjana",
    kodeDSpace: 202,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120403,
    programStudi: "Bisnis Internasional",
    jenjang: "Diploma III",
    kodeDSpace: 298,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120404,
    programStudi: "Pemasaran Digital",
    jenjang: "Diploma IV",
    kodeDSpace: 198,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120410,
    programStudi: "Ekonomi Islam",
    jenjang: "Sarjana",
    kodeDSpace: 203,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120420,
    programStudi: "Ilmu Manajemen",
    jenjang: "Magister",
    kodeDSpace: 207,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120430,
    programStudi: "Manajemen",
    jenjang: "Doktor",
    kodeDSpace: "",
    owningCollection: "code here",
  },
  {
    kodeProdi: 120510,
    programStudi: "Bisnis Digital",
    jenjang: "Sarjana",
    kodeDSpace: "",
    owningCollection: "code here",
  },
  {
    kodeProdi: 120530,
    programStudi: "Akuntansi",
    jenjang: "Doktor",
    kodeDSpace: 212,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120610,
    programStudi: "Ilmu Ekonomi",
    jenjang: "Sarjana",
    kodeDSpace: 201,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120620,
    programStudi: "Akuntansi",
    jenjang: "Magister",
    kodeDSpace: 209,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120720,
    programStudi: "Ekonomi Terapan",
    jenjang: "Magister",
    kodeDSpace: 210,
    owningCollection: "code here",
  },
  {
    kodeProdi: 120820,
    programStudi: "Manajemen",
    jenjang: "Magister",
    kodeDSpace: 208,
    owningCollection: "code here",
  },
  {
    kodeProdi: 121120,
    programStudi: "Manajemen Keuangan Mikro Terpadu",
    jenjang: "Magister",
    kodeDSpace: 318,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130103,
    programStudi: "Kebidanan",
    jenjang: "Diploma III",
    kodeDSpace: 300,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130104,
    programStudi: "Kebidanan",
    jenjang: "Diploma IV",
    kodeDSpace: 227,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130110,
    programStudi: "Kedokteran",
    jenjang: "Sarjana",
    kodeDSpace: 229,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130112,
    programStudi: "Dokter",
    jenjang: "Profesi",
    kodeDSpace: 228,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130120,
    programStudi: "Ilmu Kedokteran Dasar",
    jenjang: "Magister",
    kodeDSpace: 231,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130121,
    programStudi: "Anestesiologi dan Terapi Intensif",
    jenjang: "Spesialis-1",
    kodeDSpace: 237,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130122,
    programStudi: "Obstetri dan Ginekologi",
    jenjang: "Subspesialis",
    kodeDSpace: 320,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130130,
    programStudi: "Kedokteran",
    jenjang: "Doktor",
    kodeDSpace: 236,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130210,
    programStudi: "Kedokteran Hewan",
    jenjang: "Sarjana",
    kodeDSpace: 230,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130221,
    programStudi: "Bedah",
    jenjang: "Spesialis-1",
    kodeDSpace: 238,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130321,
    programStudi: "Bedah Saraf",
    jenjang: "Spesialis-1",
    kodeDSpace: 239,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130322,
    programStudi: "Anestesiologi dan Terapi Intensif",
    jenjang: "Subspesialis",
    kodeDSpace: 321,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130421,
    programStudi: "Obstetri dan Ginekologi",
    jenjang: "Spesialis-1",
    kodeDSpace: 249,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130422,
    programStudi: "Penyakit Dalam",
    jenjang: "Subspesialis",
    kodeDSpace: 323,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130521,
    programStudi: "Psikiatri Kedokteran Jiwa",
    jenjang: "Spesialis-1",
    kodeDSpace: 324,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130621,
    programStudi: "Kedokteran Forensik dan Studi Medikolegal",
    jenjang: "Spesialis-1",
    kodeDSpace: 325,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130721,
    programStudi: "Kesehatan Anak",
    jenjang: "Spesialis-1",
    kodeDSpace: 326,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130821,
    programStudi: "Patologi Anatomi",
    jenjang: "Spesialis-1",
    kodeDSpace: 250,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130920,
    programStudi: "Kesehatan Masyarakat",
    jenjang: "Magister",
    kodeDSpace: 232,
    owningCollection: "code here",
  },
  {
    kodeProdi: 130921,
    programStudi: "Patologi Klinik",
    jenjang: "Spesialis-1",
    kodeDSpace: 251,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131020,
    programStudi: "Kebidanan",
    jenjang: "Magister",
    kodeDSpace: 233,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131021,
    programStudi: "Penyakit Dalam",
    jenjang: "Spesialis-1",
    kodeDSpace: 244,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131121,
    programStudi: "Dermatologi dan Venereologi",
    jenjang: "Spesialis-1",
    kodeDSpace: 327,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131221,
    programStudi: "Kesehatan Mata",
    jenjang: "Spesialis-1",
    kodeDSpace: 245,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131321,
    programStudi: "Neurologi",
    jenjang: "Spesialis-1",
    kodeDSpace: 328,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131421,
    programStudi: "Kesehatan Telinga Hidung Tenggorok Bedah Kepala dan Leher",
    jenjang: "Spesialis-1",
    kodeDSpace: 248,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131520,
    programStudi: "Epidemiologi",
    jenjang: "Magister",
    kodeDSpace: 235,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131521,
    programStudi: "Radiologi",
    jenjang: "Spesialis-1",
    kodeDSpace: 252,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131620,
    programStudi: "Anti Aging dan Aesthetic Medicine",
    jenjang: "Magister",
    kodeDSpace: 234,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131621,
    programStudi: "Orthopaedi dan Traumatologi",
    jenjang: "Spesialis-1",
    kodeDSpace: 240,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131721,
    programStudi: "Kedokteran Nuklir",
    jenjang: "Spesialis-1",
    kodeDSpace: 253,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131821,
    programStudi: "Urologi",
    jenjang: "Spesialis-1",
    kodeDSpace: 255,
    owningCollection: "code here",
  },
  {
    kodeProdi: 131921,
    programStudi: "Bedah Anak",
    jenjang: "Spesialis-1",
    kodeDSpace: 254,
    owningCollection: "code here",
  },
  {
    kodeProdi: 132021,
    programStudi: "Kedokteran Fisik dan Rehabilitasi",
    jenjang: "Spesialis-1",
    kodeDSpace: 256,
    owningCollection: "code here",
  },
  {
    kodeProdi: 132121,
    programStudi: "Penyakit Jantung dan Pembuluh Darah",
    jenjang: "Spesialis-1",
    kodeDSpace: 330,
    owningCollection: "code here",
  },
  {
    kodeProdi: 132221,
    programStudi: "Kedokteran Layanan Primer",
    jenjang: "Spesialis-1",
    kodeDSpace: 259,
    owningCollection: "code here",
  },
  {
    kodeProdi: 132321,
    programStudi: "Ilmu Bedah Plastik",
    jenjang: "Spesialis-1",
    kodeDSpace: 258,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140103,
    programStudi: "Manajemen Informatika",
    jenjang: "Diploma III",
    kodeDSpace: 302,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140110,
    programStudi: "Matematika",
    jenjang: "Sarjana",
    kodeDSpace: 263,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140120,
    programStudi: "Kimia",
    jenjang: "Magister",
    kodeDSpace: 272,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140130,
    programStudi: "Kimia",
    jenjang: "Doktor",
    kodeDSpace: 277,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140203,
    programStudi: "Teknik Informatika",
    jenjang: "Diploma III",
    kodeDSpace: 303,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140210,
    programStudi: "Kimia",
    jenjang: "Sarjana",
    kodeDSpace: 264,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140220,
    programStudi: "Matematika",
    jenjang: "Magister",
    kodeDSpace: 274,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140230,
    programStudi: "Matematika",
    jenjang: "Doktor",
    kodeDSpace: 278,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140303,
    programStudi: "Teknik Komputer",
    jenjang: "Diploma III",
    kodeDSpace: 304,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140310,
    programStudi: "Fisika",
    jenjang: "Sarjana",
    kodeDSpace: 265,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140320,
    programStudi: "Biologi",
    jenjang: "Magister",
    kodeDSpace: 275,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140410,
    programStudi: "Biologi",
    jenjang: "Sarjana",
    kodeDSpace: 266,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140503,
    programStudi: "Kimia Industri",
    jenjang: "Diploma III",
    kodeDSpace: 305,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140603,
    programStudi: "Analisis Kimia",
    jenjang: "Diploma III",
    kodeDSpace: 306,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140610,
    programStudi: "Statistika",
    jenjang: "Sarjana",
    kodeDSpace: 267,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140710,
    programStudi: "Geofisika",
    jenjang: "Sarjana",
    kodeDSpace: "",
    owningCollection: "code here",
  },
  {
    kodeProdi: 140720,
    programStudi: "Statistika Terapan",
    jenjang: "Magister",
    kodeDSpace: 273,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140810,
    programStudi: "Teknik Informatika",
    jenjang: "Sarjana",
    kodeDSpace: 269,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140820,
    programStudi: "Fisika",
    jenjang: "Magister",
    kodeDSpace: 276,
    owningCollection: "code here",
  },
  {
    kodeProdi: 140910,
    programStudi: "Teknik Elektro",
    jenjang: "Sarjana",
    kodeDSpace: 270,
    owningCollection: "code here",
  },
  {
    kodeProdi: 141010,
    programStudi: "Ilmu Aktuaria",
    jenjang: "Sarjana",
    kodeDSpace: 271,
    owningCollection: "code here",
  },
  {
    kodeProdi: 150104,
    programStudi: "Agrotekno-preneur",
    jenjang: "Diploma IV",
    kodeDSpace: 73,
    owningCollection: "code here",
  },
  {
    kodeProdi: 150120,
    programStudi: "Ekonomi Pertanian",
    jenjang: "Magister",
    kodeDSpace: 76,
    owningCollection: "code here",
  },
  {
    kodeProdi: 150130,
    programStudi: "Ilmu Pertanian",
    jenjang: "Doktor",
    kodeDSpace: 79,
    owningCollection: "code here",
  },
  {
    kodeProdi: 150220,
    programStudi: "Ilmu Tanah",
    jenjang: "Magister",
    kodeDSpace: 77,
    owningCollection: "code here",
  },
  {
    kodeProdi: 150320,
    programStudi: "Agronomi",
    jenjang: "Magister",
    kodeDSpace: 78,
    owningCollection: "code here",
  },
  {
    kodeProdi: 150510,
    programStudi: "Agroteknologi",
    jenjang: "Sarjana",
    kodeDSpace: 74,
    owningCollection: "code here",
  },
  {
    kodeProdi: 150610,
    programStudi: "Agribisnis",
    jenjang: "Sarjana",
    kodeDSpace: 75,
    owningCollection: "code here",
  },
  {
    kodeProdi: 160110,
    programStudi: "Kedokteran Gigi",
    jenjang: "Sarjana",
    kodeDSpace: 83,
    owningCollection: "code here",
  },
  {
    kodeProdi: 160112,
    programStudi: "Dokter Gigi",
    jenjang: "Profesi",
    kodeDSpace: 84,
    owningCollection: "code here",
  },
  {
    kodeProdi: 160121,
    programStudi: "Bedah Mulut",
    jenjang: "Spesialis-1",
    kodeDSpace: 85,
    owningCollection: "code here",
  },
  {
    kodeProdi: 160221,
    programStudi: "Prostodontik",
    jenjang: "Spesialis-1",
    kodeDSpace: 86,
    owningCollection: "code here",
  },
  {
    kodeProdi: 160230,
    programStudi: "Ilmu Kedokteran Gigi",
    jenjang: "Doktor",
    kodeDSpace: 332,
    owningCollection: "code here",
  },
  {
    kodeProdi: 160321,
    programStudi: "Ortodontik",
    jenjang: "Spesialis-1",
    kodeDSpace: 87,
    owningCollection: "code here",
  },
  {
    kodeProdi: 160421,
    programStudi: "Kesehatan Gigi Anak",
    jenjang: "Spesialis-1",
    kodeDSpace: 88,
    owningCollection: "code here",
  },
  {
    kodeProdi: 160521,
    programStudi: "Periodontik",
    jenjang: "Spesialis-1",
    kodeDSpace: 89,
    owningCollection: "code here",
  },
  {
    kodeProdi: 160621,
    programStudi: "Konservasi Gigi",
    jenjang: "Spesialis-1",
    kodeDSpace: 90,
    owningCollection: "code here",
  },
  {
    kodeProdi: 160721,
    programStudi: "Penyakit Mulut",
    jenjang: "Spesialis-1",
    kodeDSpace: 91,
    owningCollection: "code here",
  },
  {
    kodeProdi: 160821,
    programStudi: "Radiologi Kedokteran Gigi",
    jenjang: "Spesialis-1",
    kodeDSpace: 92,
    owningCollection: "code here",
  },
  {
    kodeProdi: 160921,
    programStudi: "Bedah Mulut dan Maksilofasial",
    jenjang: "Spesialis-1",
    kodeDSpace: 333,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170103,
    programStudi: "Administrasi",
    jenjang: "Diploma III",
    kodeDSpace: 308,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170104,
    programStudi: "Administrasi Keuangan Publik",
    jenjang: "Diploma IV",
    kodeDSpace: 98,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170110,
    programStudi: "Administrasi Publik",
    jenjang: "Sarjana",
    kodeDSpace: 101,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170120,
    programStudi: "Ilmu Sosial",
    jenjang: "Magister",
    kodeDSpace: 334,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170130,
    programStudi: "Sosiologi",
    jenjang: "Doktor",
    kodeDSpace: 117,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170204,
    programStudi: "Administrasi Pemerintahan",
    jenjang: "Diploma IV",
    kodeDSpace: 97,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170210,
    programStudi: "Hubungan Internasional",
    jenjang: "Sarjana",
    kodeDSpace: 102,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170230,
    programStudi: "Ilmu Administrasi",
    jenjang: "Doktor",
    kodeDSpace: 118,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170304,
    programStudi: "Bisnis Logistik",
    jenjang: "Diploma IV",
    kodeDSpace: 99,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170310,
    programStudi: "Kesejahteraan Sosial",
    jenjang: "Sarjana",
    kodeDSpace: 103,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170320,
    programStudi: "Sosiologi",
    jenjang: "Magister",
    kodeDSpace: 112,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170330,
    programStudi: "Hubungan Internasional",
    jenjang: "Doktor",
    kodeDSpace: 119,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170404,
    programStudi: "Kearsipan Digital",
    jenjang: "Diploma IV",
    kodeDSpace: 100,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170410,
    programStudi: "Ilmu Pemerintahan",
    jenjang: "Sarjana",
    kodeDSpace: 104,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170430,
    programStudi: "Kesejahteraan Sosial",
    jenjang: "Doktor",
    kodeDSpace: 120,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170510,
    programStudi: "Antropologi",
    jenjang: "Sarjana",
    kodeDSpace: 105,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170520,
    programStudi: "Kebijakan Publik",
    jenjang: "Magister",
    kodeDSpace: 114,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170610,
    programStudi: "Administrasi Bisnis",
    jenjang: "Sarjana",
    kodeDSpace: 106,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170620,
    programStudi: "Administrasi Bisnis",
    jenjang: "Magister",
    kodeDSpace: 110,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170710,
    programStudi: "Sosiologi",
    jenjang: "Sarjana",
    kodeDSpace: 107,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170720,
    programStudi: "Administrasi Publik",
    jenjang: "Magister",
    kodeDSpace: 109,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170803,
    programStudi: "Administrasi Pemerintahan",
    jenjang: "Diploma III",
    kodeDSpace: 309,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170810,
    programStudi: "Ilmu Politik",
    jenjang: "Sarjana",
    kodeDSpace: 108,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170820,
    programStudi: "Ilmu Politik",
    jenjang: "Magister",
    kodeDSpace: 115,
    owningCollection: "code here",
  },
  {
    kodeProdi: 170910,
    programStudi: "Administrasi Bisnis K. Pangandaran",
    jenjang: "Sarjana",
    kodeDSpace: 335,
    owningCollection: "code here",
  },
  {
    kodeProdi: 171220,
    programStudi: "Antropologi",
    jenjang: "Magister",
    kodeDSpace: 111,
    owningCollection: "code here",
  },
  {
    kodeProdi: 171320,
    programStudi: "Kesejahteraan Sosial",
    jenjang: "Magister",
    kodeDSpace: 113,
    owningCollection: "code here",
  },
  {
    kodeProdi: 171520,
    programStudi: "Ilmu Pemerintahan",
    jenjang: "Magister",
    kodeDSpace: 116,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180103,
    programStudi: "Bahasa Indonesia",
    jenjang: "Diploma III",
    kodeDSpace: 311,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180104,
    programStudi: "Bahasa dan Budaya Tiongkok",
    jenjang: "Diploma IV",
    kodeDSpace: 337,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180110,
    programStudi: "Sastra Indonesia",
    jenjang: "Sarjana",
    kodeDSpace: 28,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180120,
    programStudi: "Sastra",
    jenjang: "Magister",
    kodeDSpace: 63,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180130,
    programStudi: "Sastra",
    jenjang: "Doktor",
    kodeDSpace: 68,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180203,
    programStudi: "Usaha Perjalanan Wisata",
    jenjang: "Diploma III",
    kodeDSpace: 312,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180210,
    programStudi: "Sastra Sunda",
    jenjang: "Sarjana",
    kodeDSpace: 51,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180310,
    programStudi: "Sejarah",
    jenjang: "Sarjana",
    kodeDSpace: 52,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180403,
    programStudi: "Bahasa Inggris",
    jenjang: "Diploma III",
    kodeDSpace: 313,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180410,
    programStudi: "Sastra Inggris",
    jenjang: "Sarjana",
    kodeDSpace: 56,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180510,
    programStudi: "Sastra Perancis",
    jenjang: "Sarjana",
    kodeDSpace: 57,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180603,
    programStudi: "Bahasa Jepang",
    jenjang: "Diploma III",
    kodeDSpace: 314,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180610,
    programStudi: "Sastra Jepang",
    jenjang: "Sarjana",
    kodeDSpace: 58,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180710,
    programStudi: "Sastra Rusia",
    jenjang: "Sarjana",
    kodeDSpace: 59,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180720,
    programStudi: "Kajian Budaya",
    jenjang: "Magister",
    kodeDSpace: 64,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180810,
    programStudi: "Sastra Jerman",
    jenjang: "Sarjana",
    kodeDSpace: 60,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180910,
    programStudi: "Sastra Arab",
    jenjang: "Sarjana",
    kodeDSpace: 61,
    owningCollection: "code here",
  },
  {
    kodeProdi: 180920,
    programStudi: "Linguistik",
    jenjang: "Magister",
    kodeDSpace: 65,
    owningCollection: "code here",
  },
  {
    kodeProdi: 181020,
    programStudi: "Sejarah",
    jenjang: "Magister",
    kodeDSpace: 66,
    owningCollection: "code here",
  },
  {
    kodeProdi: 190110,
    programStudi: "Psikologi",
    jenjang: "Sarjana",
    kodeDSpace: 282,
    owningCollection: "code here",
  },
  {
    kodeProdi: 190120,
    programStudi: "Psikologi",
    jenjang: "Magister",
    kodeDSpace: 283,
    owningCollection: "code here",
  },
  {
    kodeProdi: 190130,
    programStudi: "Psikologi",
    jenjang: "Doktor",
    kodeDSpace: 285,
    owningCollection: "code here",
  },
  {
    kodeProdi: 190420,
    programStudi: "Psikologi Profesi",
    jenjang: "Magister",
    kodeDSpace: 284,
    owningCollection: "code here",
  },
  {
    kodeProdi: 200110,
    programStudi: "Peternakan",
    jenjang: "Sarjana",
    kodeDSpace: 122,
    owningCollection: "code here",
  },
  {
    kodeProdi: 200120,
    programStudi: "Peternakan",
    jenjang: 125,
    owningCollection: "code here",
  },
  {
    kodeProdi: 200130,
    programStudi: "Peternakan",
    jenjang: "Doktor",
    kodeDSpace: 126,
    owningCollection: "code here",
  },
  {
    kodeProdi: 200610,
    programStudi: "Peternakan K. Pangandaran",
    jenjang: "Sarjana",
    kodeDSpace: 338,
    owningCollection: "code here",
  },
  {
    kodeProdi: 210103,
    programStudi: "Hubungan Masyarakat",
    jenjang: "Diploma III",
    kodeDSpace: 316,
    owningCollection: "code here",
  },
  {
    kodeProdi: 210104,
    programStudi: "Manajemen Produksi Media",
    jenjang: "Diploma IV",
    kodeDSpace: 131,
    owningCollection: "code here",
  },
  {
    kodeProdi: 210110,
    programStudi: "Ilmu Komunikasi",
    jenjang: "Sarjana",
    kodeDSpace: 132,
    owningCollection: "code here",
  },
  {
    kodeProdi: 210120,
    programStudi: "Ilmu Komunikasi",
    jenjang: "Magister",
    kodeDSpace: 138,
    owningCollection: "code here",
  },
  {
    kodeProdi: 210130,
    programStudi: "Ilmu Komunikasi",
    jenjang: "Doktor",
    kodeDSpace: 139,
    owningCollection: "code here",
  },
  {
    kodeProdi: 210210,
    programStudi: "Ilmu Perpustakaan",
    jenjang: "Sarjana",
    kodeDSpace: 133,
    owningCollection: "code here",
  },
  {
    kodeProdi: 210310,
    programStudi: "Hubungan Masyarakat",
    jenjang: "Sarjana",
    kodeDSpace: 134,
    owningCollection: "code here",
  },
  {
    kodeProdi: 210410,
    programStudi: "Televisi dan Film",
    jenjang: "Sarjana",
    kodeDSpace: 137,
    owningCollection: "code here",
  },
  {
    kodeProdi: 210510,
    programStudi: "Manajemen Komunikasi",
    jenjang: "Sarjana",
    kodeDSpace: 136,
    owningCollection: "code here",
  },
  {
    kodeProdi: 210610,
    programStudi: "Jurnalistik",
    jenjang: "Sarjana",
    kodeDSpace: 135,
    owningCollection: "code here",
  },
  {
    kodeProdi: 210710,
    programStudi: "Ilmu Komunikasi K. Pangandaran",
    jenjang: "Sarjana",
    kodeDSpace: 339,
    owningCollection: "code here",
  },
  {
    kodeProdi: 210810,
    programStudi: "Perpustakaan dan Sains Informasi",
    jenjang: "Sarjana",
    kodeDSpace: 340,
    owningCollection: "code here",
  },
  {
    kodeProdi: 220110,
    programStudi: "Keperawatan",
    jenjang: "Sarjana",
    kodeDSpace: 146,
    owningCollection: "code here",
  },
  {
    kodeProdi: 220112,
    programStudi: "Profesi Ners",
    jenjang: "Profesi",
    kodeDSpace: 145,
    owningCollection: "code here",
  },
  {
    kodeProdi: 220120,
    programStudi: "Keperawatan",
    jenjang: "Magister",
    kodeDSpace: 147,
    owningCollection: "code here",
  },
  {
    kodeProdi: 220210,
    programStudi: "Keperawatan K. Pangandaran",
    jenjang: "Sarjana",
    kodeDSpace: 341,
    owningCollection: "code here",
  },
  {
    kodeProdi: 230110,
    programStudi: "Perikanan",
    jenjang: "Sarjana",
    kodeDSpace: 153,
    owningCollection: "code here",
  },
  {
    kodeProdi: 230210,
    programStudi: "Ilmu Kelautan",
    jenjang: "Sarjana",
    kodeDSpace: 154,
    owningCollection: "code here",
  },
  {
    kodeProdi: 230310,
    programStudi: "Perikanan K. Pangandaran",
    jenjang: "Sarjana",
    kodeDSpace: 342,
    owningCollection: "code here",
  },
  {
    kodeProdi: 230410,
    programStudi: "Perikanan Laut Tropis",
    jenjang: "Sarjana",
    kodeDSpace: 155,
    owningCollection: "code here",
  },
  {
    kodeProdi: 230420,
    programStudi: "Perikanan",
    jenjang: "Magister",
    kodeDSpace: 157,
    owningCollection: "code here",
  },
  {
    kodeProdi: 240110,
    programStudi: "Teknik Pertanian",
    jenjang: "Sarjana",
    kodeDSpace: 160,
    owningCollection: "code here",
  },
  {
    kodeProdi: 240120,
    programStudi: "Teknologi Agroindustri",
    jenjang: "Magister",
    kodeDSpace: 164,
    owningCollection: "code here",
  },
  {
    kodeProdi: 240130,
    programStudi: "Teknologi Agroindustri",
    jenjang: "Doktor",
    kodeDSpace: 344,
    owningCollection: "code here",
  },
  {
    kodeProdi: 240210,
    programStudi: "Teknologi Pangan",
    jenjang: "Sarjana",
    kodeDSpace: 161,
    owningCollection: "code here",
  },
  {
    kodeProdi: 240310,
    programStudi: "Teknologi Industri Pertanian",
    jenjang: "Sarjana",
    kodeDSpace: 162,
    owningCollection: "code here",
  },
  {
    kodeProdi: 240320,
    programStudi: "Teknologi Industri Pertanian",
    jenjang: "Magister",
    kodeDSpace: 163,
    owningCollection: "code here",
  },
  {
    kodeProdi: 250120,
    programStudi: "Ilmu Lingkungan",
    jenjang: "Magister",
    kodeDSpace: 167,
    owningCollection: "code here",
  },
  {
    kodeProdi: 250130,
    programStudi: "Ilmu Lingkungan",
    jenjang: "Doktor",
    kodeDSpace: 173,
    owningCollection: "code here",
  },
  {
    kodeProdi: 250230,
    programStudi: "Bioteknologi",
    jenjang: "Doktor",
    kodeDSpace: 174,
    owningCollection: "code here",
  },
  {
    kodeProdi: 250620,
    programStudi: "Bioteknologi",
    jenjang: "Magister",
    kodeDSpace: 170,
    owningCollection: "code here",
  },
  {
    kodeProdi: 250720,
    programStudi: "Pariwisata Berkelanjutan",
    jenjang: "Magister",
    kodeDSpace: 169,
    owningCollection: "code here",
  },
  {
    kodeProdi: 250820,
    programStudi: "Ilmu Keberlanjutan",
    jenjang: "Magister",
    kodeDSpace: 168,
    owningCollection: "code here",
  },
  {
    kodeProdi: 250920,
    programStudi: "Manajemen Sumber Daya Hayati",
    jenjang: "Magister",
    kodeDSpace: 172,
    owningCollection: "code here",
  },
  {
    kodeProdi: 251020,
    programStudi: "Inovasi Regional",
    jenjang: "Magister",
    kodeDSpace: 171,
    owningCollection: "code here",
  },
  {
    kodeProdi: 260110,
    programStudi: "Farmasi",
    jenjang: "Sarjana",
    kodeDSpace: 180,
    owningCollection: "code here",
  },
  {
    kodeProdi: 260112,
    programStudi: "Apoteker",
    jenjang: "Profesi",
    kodeDSpace: 179,
    owningCollection: "code here",
  },
  {
    kodeProdi: 260120,
    programStudi: "Farmasi",
    jenjang: "Magister",
    kodeDSpace: 181,
    owningCollection: "code here",
  },
  {
    kodeProdi: 260130,
    programStudi: "Farmasi",
    jenjang: "Doktor",
    kodeDSpace: 183,
    owningCollection: "code here",
  },
  {
    kodeProdi: 260220,
    programStudi: "Farmasi Klinik",
    jenjang: "Magister",
    kodeDSpace: 182,
    owningCollection: "code here",
  },
  {
    kodeProdi: 270110,
    programStudi: "Teknik Geologi",
    jenjang: "Sarjana",
    kodeDSpace: 187,
    owningCollection: "code here",
  },
  {
    kodeProdi: 270120,
    programStudi: "Teknik Geologi",
    jenjang: "Magister",
    kodeDSpace: 188,
    owningCollection: "code here",
  },
  {
    kodeProdi: 270130,
    programStudi: "Teknik Geologi",
    jenjang: "Doktor",
    kodeDSpace: 189,
    owningCollection: "code here",
  },
];
